from collections.abc import Sequence
from typing import Protocol

from app.domain.admin.entities import AdminUser


class AdminRepository(Protocol):
    async def list_all(self) -> Sequence[AdminUser]: ...
    async def get_by_chat_id(self, chat_id: str) -> AdminUser | None: ...
    async def exists(self, chat_id: str) -> bool: ...
    async def add(self, admin: AdminUser) -> bool: ...
    async def delete_by_chat_id(self, chat_id: str) -> bool: ...
