from collections.abc import Sequence
from typing import Protocol

from app.domain.shifts.entities import Shift
from app.domain.shifts.value_objects import ShiftImportRow


class ShiftRepository(Protocol):
    async def clear_all(self) -> None: ...
    async def bulk_insert(self, records: list[ShiftImportRow]) -> None: ...
    async def get_by_id(self, shift_id: int) -> Shift | None: ...
    async def get_for_assistant(self, assistant_id: int, date: str, shift_type: str) -> Shift | None: ...
    async def remove_assistant(self, assistant_id: int, date: str, shift_type: str) -> None: ...
    async def add_by_id(self, assistant_id: int, assistant_name: str, shift_id: int) -> bool: ...
    async def add_manual(
        self, assistant_id: int, assistant_name: str, doctor_name: str, shift_type: str, date: str
    ) -> bool: ...
    async def add_slot(self, doctor_name: str, date: str, shift_type: str) -> bool: ...
    async def delete_by_id(self, shift_id: int) -> bool: ...
    async def list_by_date(self, date: str) -> Sequence[Shift]: ...
    async def list_all(self) -> Sequence[Shift]: ...
