[mypy]
python_version = 3.13
strict = True
check_untyped_defs = True
disallow_untyped_defs = True
disallow_untyped_calls = True
implicit_optional = False
warn_unused_ignores = True
show_error_codes = True
exclude = (?x)(^\.venv/|^dist/|^build/|^migrations/|^tests/.*/__init__\.py$)
