from collections.abc import Sequence
from typing import Protocol

from app.domain.workers.entities import Worker


class WorkerRepository(Protocol):
    async def get_by_fullname(self, full_name: str, include_inactive: bool = False) -> Worker | None: ...
    async def get_by_chat_id(self, chat_id: int, include_inactive: bool = False) -> Worker | None: ...
    async def get_by_id(self, worker_id: int, include_inactive: bool = False) -> Worker | None: ...
    async def list_all(self, include_inactive: bool = False) -> Sequence[Worker]: ...
    async def list_unregistered(self) -> Sequence[Worker]: ...
    async def add(self, worker: Worker) -> None: ...
    async def set_chat_id(self, worker_id: int, chat_id: str) -> bool: ...
    async def clear_chat_id(self, worker_id: int) -> bool: ...
    async def set_file_id(self, worker_id: int, file_id: str) -> None: ...
    async def set_active(self, worker_id: int, is_active: bool) -> bool: ...
    async def update_from_sync(
        self,
        worker_id: int,
        *,
        file_id: str | None,
        chat_id: str | None,
        speciality: str | None,
        phone: str | None,
        shifts_week: int,
        shifts_month: int,
        given_week: int,
        given_month: int,
        replacement_week: int,
        replacement_month: int,
        manual_week: int,
        manual_month: int,
        is_active: bool = True,
    ) -> bool: ...
