from collections.abc import Sequence
from typing import Protocol

from app.domain.instruments.entities import Cabinet, Instrument, InstrumentMove


class CabinetRepository(Protocol):
    async def list_all(self, include_archived: bool = False) -> Sequence[Cabinet]: ...
    async def get_by_id(self, cabinet_id: int) -> Cabinet | None: ...
    async def add(self, cabinet: Cabinet) -> None: ...
    async def update_name(self, cabinet_id: int, name: str) -> bool: ...
    async def set_active(self, cabinet_id: int, is_active: bool) -> bool: ...
    async def delete(self, cabinet_id: int) -> bool: ...
    async def has_instruments(self, cabinet_id: int) -> bool: ...


class InstrumentRepository(Protocol):
    async def list_by_cabinet(self, cabinet_id: int, include_archived: bool = False) -> Sequence[Instrument]: ...
    async def get_by_id(self, instrument_id: int) -> Instrument | None: ...
    async def update_cabinet(self, instrument_id: int, cabinet_id: int) -> bool: ...
    async def add(self, instrument: Instrument) -> None: ...
    async def update_name(self, instrument_id: int, name: str) -> bool: ...
    async def set_active(self, instrument_id: int, is_active: bool) -> bool: ...
    async def delete(self, instrument_id: int) -> bool: ...


class InstrumentMoveRepository(Protocol):
    async def add(self, move: InstrumentMove) -> None: ...
    async def list_recent(self, limit: int = 20) -> Sequence[InstrumentMove]: ...
    async def get_last_for_instrument(self, instrument_id: int) -> InstrumentMove | None: ...
    async def get_by_id(self, move_id: int) -> InstrumentMove | None: ...
