from collections.abc import Sequence
from typing import Protocol

from app.domain.knowledge_base.entities import KnowledgeItem, KnowledgeManipulation, KnowledgeSection


class KnowledgeBaseRepository(Protocol):
    async def replace_all(
        self,
        sections: Sequence[tuple[KnowledgeSection, Sequence[tuple[KnowledgeManipulation, Sequence[KnowledgeItem]]]]],
    ) -> None: ...
    async def list_sections(self) -> Sequence[KnowledgeSection]: ...
    async def get_section(self, section_id: int) -> KnowledgeSection | None: ...
    async def list_manipulations(self, section_id: int) -> Sequence[KnowledgeManipulation]: ...
    async def get_manipulation(self, manipulation_id: int) -> KnowledgeManipulation | None: ...
    async def list_items(self, manipulation_id: int) -> Sequence[KnowledgeItem]: ...
