from collections.abc import Iterable
from typing import Protocol


class AdminSyncGateway(Protocol):
    def read_workers(self) -> list[list[str]]: ...
    def read_pairs(self) -> list[list[str]]: ...
    def read_surveys(self) -> list[list[str]]: ...
    def read_shifts(self) -> list[list[str]]: ...
    def export_answers(self, headers: list[str], rows: Iterable[list[str]]) -> None: ...
    def export_shifts(self, headers: list[str], rows: Iterable[list[str]]) -> None: ...
