from collections.abc import Sequence
from typing import Protocol

from app.domain.surveys.entities import Answer, Pair, Survey


class SurveyRepository(Protocol):
    async def get_by_name(self, name: str) -> Survey | None: ...
    async def clear_all(self) -> None: ...
    async def add(self, survey: Survey) -> None: ...


class PairRepository(Protocol):
    async def list_ready_by_date(self, date: str) -> Sequence[Pair]: ...
    async def next_ready_for_subject(self, subject: str) -> Pair | None: ...
    async def update_status(self, pair_id: int, status: str) -> None: ...
    async def reset_incomplete(self) -> None: ...
    async def add(self, pair: Pair) -> None: ...
    async def clear_all(self) -> None: ...


class AnswerRepository(Protocol):
    async def save(self, answer: Answer) -> None: ...
    async def list_all(self) -> Sequence[Answer]: ...
